ALTER TABLE public.footballer_clubs DISABLE TRIGGER ALL;
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (1, 1, 1);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (2, 2, 2);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (3, 3, 3);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (4, 4, 4);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (5, 5, 5);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (6, 6, 6);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (7, 7, 7);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (8, 8, 8);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (9, 9, 9);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (10, 11, 10);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (11, 10, 11);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (12, 12, 12);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (13, 13, 13);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (14, 12, 1);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (15, 13, 2);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (16, 12, 11);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (17, 14, 10);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (18, 14, 11);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (19, 15, 1);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (20, 16, 4);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (21, 17, 5);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (22, 18, 6);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (23, 19, 7);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (24, 20, 8);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (25, 21, 9);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (26, 22, 10);
INSERT INTO public.footballer_clubs(footballer_club_id, player_id, club_id) VALUES (27, 23, 11);
select * from public.footballer_clubs;
ALTER TABLE public.footballer_clubs ENABLE TRIGGER ALL;