ALTER TABLE public.football_clubs_seasones DISABLE TRIGGER ALL;
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (1, 1, 1);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (2, 2, 2);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (3, 3, 3);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (4, 4, 4);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (5, 5, 5);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (6, 6, 6);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (7, 7, 7);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (8, 8, 8);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (9, 9, 9);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (10, 10, 10);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (11, 10, 11);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (12, 1, 13);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (13, 3, 11);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (14, 3, 5);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (15, 2, 9);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (16, 1, 8);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (17, 5, 12);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (18, 2, 13);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (19, 7, 4);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (20, 9, 7);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (21, 1, 3);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (22, 7, 12);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (23, 3, 13);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (24, 8, 9);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (25, 10, 10);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (26, 1, 13);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (27, 1, 11);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (28, 1, 4);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (29, 7, 7);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (30, 2, 6);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (31, 9, 9);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (32, 5, 12);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (33, 1, 3);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (34, 4, 1);
insert into public.football_clubs_seasones (football_clubs_season_id, season_id  , club_id  ) values (35, 2, 9);
select * from public.football_clubs_seasones;
ALTER TABLE public.football_clubs_seasones ENABLE TRIGGER ALL;
