ALTER TABLE organization.addresses DISABLE TRIGGER ALL;
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (1, '8762 Esch Circle', 'Daytona Beach', 'United States', 'Florida', '32128');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (2, '89 Myrtle Alley', 'Saint Petersburg', 'United States', 'Florida', '33710');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (3, '456 Menomonie Pass', 'Bradenton', 'United States', 'Florida', '34210');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (4, '36 Brown Drive', 'Staten Island', 'United States', 'New York', '10310');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (5, '707 Hanover Terrace', 'Fairfax', 'United States', 'Virginia', '22036');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (6, '3298 Waxwing Alley', 'Saint Paul', 'United States', 'Minnesota', '55108');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (7, '0628 1st Court', 'Los Angeles', 'United States', 'California', '90081');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (8, '3867 Steensland Street', 'Sacramento', 'United States', 'California', '94257');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (9, '464 Eastlawn Crossing', 'Saint Augustine', 'United States', 'Florida', '32092');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (10, '015 Jackson Court', 'Indianapolis', 'United States', 'Indiana', '46221');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (11, '9 Cordelia Street', 'Boston', 'United States', 'Massachusetts', '02109');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (12, '2793 Donald Junction', 'Memphis', 'United States', 'Tennessee', '38109');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (13, '94 Sauthoff Point', 'New Brunswick', 'United States', 'New Jersey', '08922');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (14, '901 Prairie Rose Way', 'Manassas', 'United States', 'Virginia', '22111');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (15, '9 Di Loreto Street', 'Salt Lake City', 'United States', 'Utah', '84145');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (16, '3 Killdeer Center', 'Lansing', 'United States', 'Michigan', '48919');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (17, '3 Grayhawk Alley', 'Oceanside', 'United States', 'California', '92056');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (18, '5130 Michigan Point', 'El Paso', 'United States', 'Texas', '79989');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (19, '016 Macpherson Avenue', 'New York City', 'United States', 'New York', '10110');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (20, '885 Ridgeway Road', 'Lincoln', 'United States', 'Nebraska', '68505');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (21, '009 Lyons Street', 'Akron', 'United States', 'Ohio', '44305');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (22, '5114 Ohio Junction', 'Omaha', 'United States', 'Nebraska', '68134');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (23, '658 8th Alley', 'Phoenix', 'United States', 'Arizona', '85077');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (24, '5227 Kingsford Trail', 'Rockville', 'United States', 'Maryland', '20851');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (25, '3077 Oxford Pass', 'Albany', 'United States', 'New York', '12222');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (26, '0 Westerfield Circle', 'Long Beach', 'United States', 'California', '90847');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (27, '48489 Rutledge Drive', 'Portland', 'United States', 'Oregon', '97229');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (28, '80996 Debs Alley', 'Biloxi', 'United States', 'Mississippi', '39534');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (29, '39 Mcbride Court', 'Colorado Springs', 'United States', 'Colorado', '80930');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (30, '6 Jenna Parkway', 'Houston', 'United States', 'Texas', '77228');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (31, '3 Goodland Way', 'Glendale', 'United States', 'California', '91205');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (32, '1300 Lillian Circle', 'Orlando', 'United States', 'Florida', '32891');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (33, '1404 Fair Oaks Pass', 'Suffolk', 'United States', 'Virginia', '23436');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (34, '104 Kedzie Point', 'Sacramento', 'United States', 'California', '95833');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (35, '4 Sage Lane', 'Des Moines', 'United States', 'Iowa', '50369');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (36, '4967 Jay Drive', 'New York City', 'United States', 'New York', '10175');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (37, '13537 Waxwing Trail', 'Stockton', 'United States', 'California', '95205');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (38, '319 Nancy Hill', 'New Haven', 'United States', 'Connecticut', '06510');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (39, '4006 Express Terrace', 'Newton', 'United States', 'Massachusetts', '02162');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (40, '8742 Lake View Court', 'Houston', 'United States', 'Texas', '77055');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (41, '40 Caliangt Center', 'Charlotte', 'United States', 'North Carolina', '28215');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (42, '309 Center Hill', 'Charlotte', 'United States', 'North Carolina', '28225');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (43, '962 Ryan Way', 'Anaheim', 'United States', 'California', '92812');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (44, '9665 Amoth Court', 'Wichita', 'United States', 'Kansas', '67210');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (45, '02364 Westport Terrace', 'Colorado Springs', 'United States', 'Colorado', '80915');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (46, '911 Butternut Circle', 'Pittsburgh', 'United States', 'Pennsylvania', '15266');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (47, '309 Lighthouse Bay Road', 'Canton', 'United States', 'Ohio', '44710');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (48, '730 Glendale Parkway', 'Flint', 'United States', 'Michigan', '48555');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (49, '3 Susan Lane', 'Las Vegas', 'United States', 'Nevada', '89105');
insert into organization.addresses (address_id, street_address, city, country, state_province, postal_code) values (50, '9 Talisman Point', 'Beaumont', 'United States', 'Texas', '77713');
select * from organization.addresses ;
ALTER TABLE organization.addresses ENABLE TRIGGER ALL;