export const FETCH_RESULTS_WITH_PLAYERS_SUCCESS = 'FETCH_RESULTS_WITH_PLAYERS_SUCCESS ';
export const FETCH_RESULTS_WITH_PLAYERS_ERROR = 'FETCH_RESULTS_WITH_PLAYERS_ERROR';
export const FETCH_RESULTS_WITH_PLAYERS_REQUEST = 'FETCH_RESULTS_WITH_PLAYERS_REQUEST';
export const FETCH_RESULT_BY_MATCH_ID_SUCCESS  = 'FETCH_RESULT_BY_MATCH_ID_SUCCESS ';
export const FETCH_RESULT_BY_MATCH_ID_ERROR = 'FETCH_RESULT_BY_MATCH_ID_ERROR';
